### ISSUE TITLE
"Most common git screwups/questions and solutions"

### ISSUE THREAD

**Issue by poliveira89** [equalsraf/git-talk#1]
Source: http://41j.com/blog/2015/02/common-git-screwupsquestions-solutions/

I think you could use some of this suggestions to "complete" your presentation. :+1: 
For me, IMHO, could be interesting to ear about: submodules and their usage.

**Comment by equalsraf** [comment]
Cheers. Neat article added the link to the slides.

I suppose we can start a new slide deck for submodules. But they are not a very consensual topic, some people love them, others hate them :D, here is a good piece about [why](https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407).

I usually hesitate to go into the topic, since it is prone to error, and you probably should avoid submodules if you can.

**Comment by poliveira89** [comment]
So, if that is the case, ignore the suggestion on submodules! :+1:
